apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ms
  name: cartoes-app
  labels:
    app: cartoes
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cartoes
  template:
    metadata:
      labels:
        app: cartoes
    spec:
      containers:
        - name: cartoes-container
          image: sergiodiogoti/cartoes:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          readinessProbe:
            initialDelaySeconds: 20
            successThreshold: 1
            failureThreshold: 5
            periodSeconds: 5
            httpGet:
              port: 8080
              path: /actuator/health
          livenessProbe:
            initialDelaySeconds: 20
            failureThreshold: 3
            periodSeconds: 10
            successThreshold: 1
            httpGet:
              port: 8080
              path: /actuator/health
