apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ms
  name: redis-acme
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      name: redis-acme
      labels:
        app: redis
    spec:
      containers:
        - name: redis-acme
          image: redis:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
      restartPolicy: Always