apiVersion: v1
kind: Service
metadata:
  namespace: ms
  name: cartoes-service
spec:
  selector:
    app: cartoes
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort

