apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: ms
  labels:
    grafana_datasource: "1"
data:
  prometheus.yaml: |
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-service.ms.svc.cluster.local:9090
        isDefault: true
        editable: true
