name: Build, Push e Deploy no K8s

on:
  push:
    branches: [ "main" ]

jobs:
  build-push-deploy:
    runs-on: self-hosted  # precisa do runner local!

    env:
      IMAGE_NAME: sergiodiogoti/cartoes

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Setup do Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build do JAR
        run: ./mvnw clean package -DskipTests

      - name: Build da imagem Docker
        run: docker build -f docker/Dockerfile -t sergiodiogoti/cartoes:latest .

      - name: Docker Login
        run: |
          echo "${{ secrets.PASS_DOCKER }}" | docker login --username "${{ secrets.USER_DOCKER }}" --password-stdin

      - name: Push da imagem
        run: docker push $IMAGE_NAME:latest

      - name: Apply YAMLs do Kubernetes
        run: kubectl apply -f k8s/ -R -n ms

      - name: Restart no Deployment
        run: kubectl rollout restart deployment cartoes-app -n ms
